### ISSUE TITLE
Compat Issue with Requiem

### ISSUE THREAD

**Issue by MLMII** [LemmaEOF/ShulkerCharm#1]
Just wanted to report an issue with Requiem, with Shulker Charm installed you lose the ability to fly while in "spirit form" after dying but before finding an undead host.
 
Thank you for your time,
 
https://www.curseforge.com/minecraft/mc-mods/requiem

**Comment by LemmaEOF** [comment]
Expected as much. Both Shulker Charm and Requiem are messing with the player's ability to fly, and they collide with each other. I know how to fix this, and I'll contact the Requiem dev so they and I can work together on it.

**Comment by MADodds1337** [comment]
I'm wondering if this is similar to the issues I'm having running your mod in conjunction with ToolBuilder...

**Comment by LemmaEOF** [comment]
Not related to ToolBuilder. ToolBuilder's problems are entirely different.

**Comment by MADodds1337** [comment]
Good to know.

**Comment by LemmaEOF** [comment]
Fixed with version 1.1.0!
