### ISSUE TITLE
Mod ignoring config

### ISSUE THREAD

**Issue by PanoptesDreams** [LemmaEOF/ShulkerCharm#2]
Modifying config file does not change in game values

**Comment by LemmaEOF** [comment]
Did you restart the game in between editing the config and testing? I currently only load config from the file on game start.

**Comment by PanoptesDreams** [comment]
Yes. I have tried all sorts, and it just doesn't work.

Anything you need, logs, additional screenshots, just ask.

(As you can see here the config things have changed but it hasn't gone trough even in a freshly generated world)
![8hviY4iaSj](https://user-images.githubusercontent.com/55162814/71569076-4fc62900-2b31-11ea-8471-afd52ac16348.png)

**Comment by LemmaEOF** [comment]
Oh, wait. I know exactly why this is happening lol, I just fixed it on another project. I'll push a fix for this soon; there's a couple other issues I need to hammer out alongside this one.

**Comment by PanoptesDreams** [comment]
Oh, wonderful. Thanks for quick response :)

**Comment by LemmaEOF** [comment]
Fixed with 1.1.0!
