### ISSUE TITLE
requires jankson 2.0

### ISSUE THREAD

**Issue by obesevran** [LemmaEOF/ShulkerCharm#5]
It says it requires jankson 2.0 but i can only find up to Jankson-1.0.0+j1.1.2.jar. do you know where this can be found.

**Comment by LemmaEOF** [comment]
Jankson 2.0 should be included inside the Shulker Charm jar itself. If it's not working, you can download Jankson [here](http://server.bbkr.space:8081/artifactory/libs-release/io/github/cottonmc/Jankson-Fabric/2.0.1+j1.2.0/Jankson-Fabric-2.0.1+j1.2.0.jar).

**Comment by obesevran** [comment]
Its working now I was stupid. I had looked at the dependencies listed on curseforge for it and downloaded latest jankson I could find. Running it without the downloaded jankson and it works fine. 
Thankyou though for the quick response, I only tried it by itself after the file you gave me didn't work either and your explanation. apologies on my part. TY very much.
