### ISSUE TITLE
Shulker Charm Drains Beyond 0

### ISSUE THREAD

**Issue by milkev** [LemmaEOF/ShulkerCharm#7]
I have my config set to limit the shulker charm to 60 max energy, i dont know if it matters, but thats something i have done.

When the player has the shulker charm equipped, and has access to creative flight through other means, such as creative or azurdooms angel ring, the shulker charm will drain and go into negative values.
![image](https://user-images.githubusercontent.com/22010128/105725112-cc1e6d80-5ee5-11eb-9740-181129fb81c0.png)

it also seems to cause a yellow bar to appear on the screen. This only appears when the shulker charm is equipped and below 0 charge. It will dissapear while the trinkets "menu" is scrolled over/open. Should be resolved if the primary issue here is resolved.
![2021-01-25_08 17 18](https://user-images.githubusercontent.com/22010128/105725204-e7897880-5ee5-11eb-8bc3-49abe1a0a0d7.png)

**Comment by LemmaEOF** [comment]
huh.

i should be able to fix this later today hopefully

**Comment by LemmaEOF** [comment]
actually I was able to do it before I fall back asleep pushing a release now
